### PR TITLE
removed svg/svg-paths

### PR DESCRIPTION
**Pull request by pebutler3**

### CODE REVIEW

**Review by moghya — CHANGES_REQUESTED** [review]
@pebutler3 Thanks for  showing interest in the project but, It was not about just removing paths.

Please understand the code in js/index.js 
We gotta add icons using svg images and not the path

**Comment by pebutler3** [comment]
Well that certainly makes more sense. 

The issue wasn't very informative.

**Comment by moghya** [comment]
@pebutler3 Sorry for that, are you interested in working upon it ?
If yes I'll assign it to you. +1:

**Comment by pebutler3** [comment]
@moghya so just add the actual svg code to the profile.json?

I can do that.

**Comment by moghya** [comment]
@pebutler3  #1 I have updated the description of issue. let me know if you can work on it.

**Comment by pebutler3** [comment]
I can do this. Just assign to me.

**Pull request closed without merging**
